import {
  approvalRequestSchema,
  blockCardRequestSchema,
  cardAuthorisationSchema,
  cardDetailSchema,
  cardQuerySchema,
  expireHoldRequestSchema,
  issueCardRequestSchema,
  itemsEnvelopeSchema,
  kpiSchema,
  ledgerIntegrityReportSchema,
  manualPostingRequestSchema,
  monitorEntrySchema,
  reissueCardRequestSchema,
  systemHealthSchema,
  trialBalanceSchema,
  updateCardLimitsRequestSchema,
} from '../../../src/index.js';
import { idSchema } from '../../../src/common/primitives.js';
import { cursorQuerySchema } from '../../../src/common/pagination.js';
import { PAGE_SCHEMAS } from '../components.js';
import { STATUS, TAG } from '../constants.js';
import { defineOperations, success } from '../spec.js';

const CARD_ID = { cardId: idSchema } as const;

export const adminOperations = defineOperations([
  {
    method: 'get',
    path: '/admin/kpis',
    tag: TAG.admin,
    operationId: 'listAdminKpis',
    summary: 'Headline ops figures with trends (staff)',
    response: success(STATUS.ok, 'The current KPI set.', itemsEnvelopeSchema(kpiSchema)),
  },
  {
    method: 'get',
    path: '/admin/monitor',
    tag: TAG.admin,
    operationId: 'monitorTransactions',
    summary: 'The global transaction monitor (staff)',
    response: success(
      STATUS.ok,
      'Recent postings across the bank.',
      itemsEnvelopeSchema(monitorEntrySchema),
    ),
  },
  {
    method: 'get',
    path: '/admin/ledger-integrity',
    tag: TAG.admin,
    operationId: 'verifyLedgerIntegrity',
    summary: 'Re-verify the ledger hash chain on demand (staff)',
    response: success(STATUS.ok, 'The integrity report.', ledgerIntegrityReportSchema),
  },
  {
    method: 'post',
    path: '/admin/postings',
    tag: TAG.admin,
    operationId: 'createManualPosting',
    summary: 'Manual credit/debit — double-entry, reasoned, four-eyes (staff)',
    request: manualPostingRequestSchema,
    idempotent: true,
    response: success(
      STATUS.created,
      'The approval request; the posting lands once a second operator approves.',
      approvalRequestSchema,
    ),
    errors: [
      { status: STATUS.notFound, description: 'The account does not exist.' },
      { status: STATUS.unprocessable },
    ],
  },
  {
    method: 'get',
    path: '/admin/trial-balance',
    tag: TAG.admin,
    operationId: 'getTrialBalance',
    summary: 'The trial balance — proof the books add up (staff)',
    response: success(STATUS.ok, 'The trial balance.', trialBalanceSchema),
  },
  {
    method: 'get',
    path: '/admin/health',
    tag: TAG.admin,
    operationId: 'getSystemHealth',
    summary: 'Component, queue, and version health (staff)',
    response: success(STATUS.ok, 'System health.', systemHealthSchema),
  },
  {
    method: 'get',
    path: '/admin/cards',
    tag: TAG.admin,
    operationId: 'listCardsForStaff',
    summary: 'Search cards across customers (staff)',
    query: cardQuerySchema,
    response: success(STATUS.ok, 'A cursor page of cards.', PAGE_SCHEMAS.CardSummaryPage),
  },
  {
    method: 'post',
    path: '/admin/cards',
    tag: TAG.admin,
    operationId: 'issueCardForStaff',
    summary: 'Issue a card on a customer’s account (staff)',
    request: issueCardRequestSchema,
    idempotent: true,
    response: success(STATUS.created, 'The issued card.', cardDetailSchema),
    errors: [{ status: STATUS.unprocessable }],
  },
  {
    method: 'get',
    path: '/admin/cards/{cardId}',
    tag: TAG.admin,
    operationId: 'getCardForStaff',
    summary: 'Card detail without customer scoping (staff)',
    pathParams: CARD_ID,
    response: success(STATUS.ok, 'The card.', cardDetailSchema),
    errors: [{ status: STATUS.notFound }],
  },
  {
    method: 'post',
    path: '/admin/cards/{cardId}/block',
    tag: TAG.admin,
    operationId: 'blockCard',
    summary: 'Block a card the customer cannot unblock themselves (staff)',
    pathParams: CARD_ID,
    request: blockCardRequestSchema,
    idempotent: true,
    response: success(STATUS.ok, 'The blocked card.', cardDetailSchema),
    errors: [{ status: STATUS.notFound }, { status: STATUS.conflict }],
  },
  {
    method: 'post',
    path: '/admin/cards/{cardId}/reissue',
    tag: TAG.admin,
    operationId: 'reissueCard',
    summary: 'Retire the PAN and issue a replacement (staff)',
    pathParams: CARD_ID,
    request: reissueCardRequestSchema,
    idempotent: true,
    response: success(STATUS.ok, 'The replacement card.', cardDetailSchema),
    errors: [{ status: STATUS.notFound }, { status: STATUS.conflict }],
  },
  {
    method: 'post',
    path: '/admin/cards/{cardId}/pin-reset',
    tag: TAG.admin,
    operationId: 'resetCardPin',
    summary: 'Clear the PIN; the customer sets the new one (staff)',
    pathParams: CARD_ID,
    idempotent: true,
    response: success(STATUS.ok, 'The card, now without a PIN.', cardDetailSchema),
    errors: [{ status: STATUS.notFound }, { status: STATUS.conflict }],
  },
  {
    method: 'patch',
    path: '/admin/cards/{cardId}/limits',
    tag: TAG.admin,
    operationId: 'updateCardLimitsForStaff',
    summary: 'Raise or lower spend limits (staff)',
    pathParams: CARD_ID,
    request: updateCardLimitsRequestSchema,
    response: success(STATUS.ok, 'The updated card.', cardDetailSchema),
    errors: [{ status: STATUS.notFound }, { status: STATUS.unprocessable }],
  },
  {
    method: 'get',
    path: '/admin/cards/{cardId}/authorisations',
    tag: TAG.admin,
    operationId: 'listCardAuthorisationsForStaff',
    summary: 'Authorisation events for one card (staff)',
    pathParams: CARD_ID,
    query: cursorQuerySchema,
    response: success(
      STATUS.ok,
      'A cursor page of authorisations.',
      PAGE_SCHEMAS.CardAuthorisationPage,
    ),
    errors: [{ status: STATUS.notFound }],
  },
  {
    method: 'post',
    path: '/admin/cards/{cardId}/authorisations/{authorisationId}/expire',
    tag: TAG.admin,
    operationId: 'expireCardAuthorisation',
    summary: 'Force-expire an open authorisation hold (staff)',
    pathParams: { cardId: idSchema, authorisationId: idSchema },
    request: expireHoldRequestSchema,
    idempotent: true,
    response: success(STATUS.ok, 'The expired authorisation.', cardAuthorisationSchema),
    errors: [
      { status: STATUS.notFound },
      { status: STATUS.conflict, description: 'The hold is already settled or expired.' },
    ],
  },
]);
