import { describe, expect, it, vi } from 'vitest';

import { buildAssetRef } from '../asset-ref.js';
import { CloudinaryAssetStore, type CloudinaryStoreConfig } from '../cloudinary-store.js';
import { UnsupportedMediaTypeError, TransformationNotSupportedError } from '../errors.js';
import type {
  CloudinaryAssetLocator,
  CloudinaryDeliveryRequest,
  CloudinaryPorts,
  CloudinaryUploadRequest,
} from '../ports.js';

const NOW = 1_700_000_000_000;
const CONFIG: CloudinaryStoreConfig = {
  cloudName: 'icb-cloud',
  apiKey: 'key-123',
  rootFolder: 'icb',
};

interface FakePorts extends CloudinaryPorts {
  signed: CloudinaryDeliveryRequest[];
  uploaded: CloudinaryUploadRequest[];
  destroyed: CloudinaryAssetLocator[];
  signParams: ReturnType<typeof vi.fn>;
}

function fakePorts(): FakePorts {
  const signed: CloudinaryDeliveryRequest[] = [];
  const uploaded: CloudinaryUploadRequest[] = [];
  const destroyed: CloudinaryAssetLocator[] = [];
  const signParams = vi.fn().mockReturnValue('deadbeefsignature');

  return {
    signed,
    uploaded,
    destroyed,
    signParams,
    uploads: {
      signParams: (params) => String(signParams(params)),
      upload: (request) => {
        uploaded.push(request);
        return Promise.resolve({
          publicId: `${request.folder}/${request.publicId}`,
          resourceType: request.resourceType,
          format: 'pdf',
          bytes: request.bytes.byteLength,
        });
      },
      destroy: (locator) => {
        destroyed.push(locator);
        return Promise.resolve();
      },
    },
    delivery: {
      signedUrl: (request) => {
        signed.push(request);
        return `https://res.cloudinary.com/icb-cloud/${request.resourceType}/authenticated/s--sig--/${request.publicId}`;
      },
    },
  };
}

function makeStore(ports: CloudinaryPorts = fakePorts(), config = CONFIG): CloudinaryAssetStore {
  return new CloudinaryAssetStore(config, ports, { now: () => NOW, generateId: () => 'uid-1' });
}

const IMAGE_REF = buildAssetRef({
  publicId: 'icb/kyc/cus_1/passport-uid-1',
  resourceType: 'image',
  uploadedAt: '2026-01-15T10:30:00.000Z',
});

const PDF_REF = buildAssetRef({
  publicId: 'icb/statements/acc_1/statement-uid-1',
  resourceType: 'raw',
  format: 'pdf',
  uploadedAt: '2026-01-15T10:30:00.000Z',
});

describe('mintUploadSignature', () => {
  it('mints a cloudinary-shaped grant following the folder/public-id conventions', () => {
    const ports = fakePorts();
    const grant = makeStore(ports).mintUploadSignature({
      kind: 'kyc',
      ownerId: 'cus_1',
      contentType: 'image/jpeg',
      sizeBytes: 500_000,
      label: 'Passport',
    });

    expect(grant).toEqual({
      uploadUrl: 'https://api.cloudinary.com/v1_1/icb-cloud/image/upload',
      publicId: 'passport-uid-1',
      folder: 'icb/kyc/cus_1',
      timestamp: 1_700_000_000,
      signature: 'deadbeefsignature',
      apiKey: 'key-123',
      expiresAt: '2023-11-14T22:18:20.000Z',
      type: 'authenticated',
    });
    expect(ports.signParams).toHaveBeenCalledWith({
      folder: 'icb/kyc/cus_1',
      public_id: 'passport-uid-1',
      timestamp: 1_700_000_000,
      type: 'authenticated',
    });
  });

  it('targets the raw endpoint for PDFs and defaults the label to the kind', () => {
    const grant = makeStore().mintUploadSignature({
      kind: 'dispute-evidence',
      ownerId: 'disp_1',
      contentType: 'application/pdf',
      sizeBytes: 100,
    });
    expect(grant.uploadUrl).toContain('/raw/upload');
    expect(grant.publicId).toBe('dispute-evidence-uid-1');
  });

  it('honours a configured signature TTL', () => {
    const store = makeStore(fakePorts(), { ...CONFIG, uploadSignatureTtlSeconds: 60 });
    const grant = store.mintUploadSignature({
      kind: 'avatars',
      ownerId: 'cus_1',
      contentType: 'image/png',
      sizeBytes: 100,
    });
    expect(grant.expiresAt).toBe('2023-11-14T22:14:20.000Z');
  });

  it('refuses to sign an upload outside the allow-list', () => {
    expect(() =>
      makeStore().mintUploadSignature({
        kind: 'avatars',
        ownerId: 'cus_1',
        contentType: 'image/gif',
        sizeBytes: 100,
      }),
    ).toThrow(UnsupportedMediaTypeError);
  });
});

describe('upload', () => {
  it('places generated bytes under the conventional folder and returns a valid ref', async () => {
    const ports = fakePorts();
    const ref = await makeStore(ports).upload({
      kind: 'statements',
      ownerId: 'acc_1',
      contentType: 'application/pdf',
      bytes: new Uint8Array([37, 80, 68, 70]),
      label: 'Statement 2026-01',
      originalFilename: 'statement-2026-01.pdf',
    });

    expect(ports.uploaded[0]).toMatchObject({
      folder: 'icb/statements/acc_1',
      publicId: 'statement-2026-01-uid-1',
      resourceType: 'raw',
    });
    expect(ref).toEqual({
      provider: 'cloudinary',
      publicId: 'icb/statements/acc_1/statement-2026-01-uid-1',
      resourceType: 'raw',
      format: 'pdf',
      bytes: 4,
      originalFilename: 'statement-2026-01.pdf',
      uploadedAt: '2023-11-14T22:13:20.000Z',
    });
  });

  it('applies the allow-list to the real byte length', async () => {
    await expect(
      makeStore().upload({
        kind: 'statements',
        ownerId: 'acc_1',
        contentType: 'image/png',
        bytes: new Uint8Array([1]),
      }),
    ).rejects.toThrow(UnsupportedMediaTypeError);
  });
});

describe('buildSignedUrl', () => {
  it('passes the preset transformation through to the delivery port', () => {
    const ports = fakePorts();
    const link = makeStore(ports).buildSignedUrl(IMAGE_REF, undefined, {
      preset: 'document-thumbnail',
    });

    expect(link.url).toContain('s--sig--');
    expect(ports.signed[0]?.transformation).toMatchObject({ width: 300, height: 300 });
    expect(ports.signed[0]?.expiresAtEpochSeconds).toBe(1_700_000_300);
    expect(link.expiresAt).toBe('2023-11-14T22:18:20.000Z');
  });

  it('omits the transformation when no preset is requested', () => {
    const ports = fakePorts();
    makeStore(ports).buildSignedUrl(IMAGE_REF);
    expect(ports.signed[0]).not.toHaveProperty('transformation');
    expect(ports.signed[0]?.attachment).toBe(false);
  });

  it('carries the format and attachment flag for a downloaded raw asset', () => {
    const ports = fakePorts();
    makeStore(ports).buildSignedUrl(PDF_REF, 120, { download: true });
    expect(ports.signed[0]?.format).toBe('pdf');
    expect(ports.signed[0]?.attachment).toBe(true);
    expect(ports.signed[0]?.expiresAtEpochSeconds).toBe(1_700_000_120);
  });

  it('rejects a transformation preset for a raw asset', () => {
    expect(() =>
      makeStore().buildSignedUrl(PDF_REF, undefined, { preset: 'document-thumbnail' }),
    ).toThrow(TransformationNotSupportedError);
  });

  it('honours a per-call TTL override', () => {
    const link = makeStore().buildSignedUrl(IMAGE_REF, 30);
    expect(link.expiresAt).toBe('2023-11-14T22:13:50.000Z');
  });
});

describe('destroy', () => {
  it('forwards the public id and resource type to the provider', async () => {
    const ports = fakePorts();
    await makeStore(ports).destroy(PDF_REF);
    expect(ports.destroyed).toEqual([
      { publicId: 'icb/statements/acc_1/statement-uid-1', resourceType: 'raw' },
    ]);
  });
});
