import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import { assetRefSchema } from '@icb/contracts';

import { LocalAssetStore } from '../local-store.js';
import { UnsafeAssetPathError, UnsupportedMediaTypeError } from '../errors.js';

const NOW = 1_700_000_000_000;

let rootDir: string;

function makeStore(overrides: Partial<ConstructorParameters<typeof LocalAssetStore>[0]> = {}) {
  return new LocalAssetStore(
    { rootDir, baseUrl: 'http://localhost:3001', ...overrides },
    { now: () => NOW, generateId: () => 'uid-1' },
  );
}

async function savePassport(store: LocalAssetStore) {
  return store.save({
    folder: 'icb/kyc/cus_1',
    publicId: 'passport-uid-1',
    contentType: 'image/png',
    bytes: new Uint8Array([1, 2, 3, 4]),
  });
}

beforeEach(async () => {
  rootDir = await mkdtemp(join(tmpdir(), 'icb-media-'));
});

afterEach(async () => {
  await rm(rootDir, { recursive: true, force: true });
});

describe('mintUploadSignature', () => {
  it('mirrors the cloudinary grant shape against the local upload endpoint', () => {
    const grant = makeStore().mintUploadSignature({
      kind: 'kyc',
      ownerId: 'cus_1',
      contentType: 'image/png',
      sizeBytes: 100,
      label: 'passport',
    });

    expect(grant.uploadUrl).toBe('http://localhost:3001/v1/media/local-upload');
    expect(grant.apiKey).toBe('local');
    expect(grant.folder).toBe('icb/kyc/cus_1');
    expect(grant.publicId).toBe('passport-uid-1');
    expect(grant.signature).toMatch(/^[0-9a-f]{40}$/);
    expect(grant.expiresAt).toBe('2023-11-14T22:18:20.000Z');
    expect(grant.type).toBe('authenticated');
  });

  it('accepts a custom upload path and TTL', () => {
    const grant = makeStore({ uploadPath: '/upload-here', uploadSignatureTtlSeconds: 10 })
      .mintUploadSignature({ kind: 'avatars', ownerId: 'cus_1', contentType: 'image/png', sizeBytes: 1 });
    expect(grant.uploadUrl).toBe('http://localhost:3001/upload-here');
    expect(grant.expiresAt).toBe('2023-11-14T22:13:30.000Z');
  });
});

describe('upload', () => {
  it('persists API-generated bytes under the conventions and returns a contract-valid ref', async () => {
    const store = makeStore();
    const ref = await store.upload({
      kind: 'statements',
      ownerId: 'acc_1',
      contentType: 'application/pdf',
      bytes: new Uint8Array([37, 80, 68, 70]),
      label: 'statement',
      originalFilename: 'january.pdf',
    });

    expect(assetRefSchema.safeParse(ref).success).toBe(true);
    expect(ref).toMatchObject({
      provider: 'cloudinary',
      publicId: 'icb/statements/acc_1/statement-uid-1',
      resourceType: 'raw',
      format: 'pdf',
      bytes: 4,
      originalFilename: 'january.pdf',
    });
    await readFile(join(rootDir, 'icb/statements/acc_1/statement-uid-1.pdf'));
  });

  it('enforces the allow-list on the real byte length', async () => {
    await expect(
      makeStore().upload({
        kind: 'avatars',
        ownerId: 'cus_1',
        contentType: 'image/gif',
        bytes: new Uint8Array([1]),
      }),
    ).rejects.toThrow(UnsupportedMediaTypeError);
  });
});

describe('save', () => {
  it('persists browser-posted bytes at the minted location', async () => {
    const ref = await savePassport(makeStore());
    expect(ref.publicId).toBe('icb/kyc/cus_1/passport-uid-1');
    const persisted = await readFile(join(rootDir, 'icb/kyc/cus_1/passport-uid-1.png'));
    expect(persisted).toEqual(Buffer.from([1, 2, 3, 4]));
  });

  it('refuses paths that could escape the storage root', async () => {
    await expect(
      makeStore().save({
        folder: '../outside',
        publicId: 'x',
        contentType: 'image/png',
        bytes: new Uint8Array([1]),
      }),
    ).rejects.toThrow(UnsafeAssetPathError);
  });
});

describe('buildSignedUrl', () => {
  it('embeds an expiry and a verifiable HMAC', async () => {
    const store = makeStore();
    const ref = await savePassport(store);

    const link = store.buildSignedUrl(ref);
    const url = new URL(link.url);
    const exp = Number(url.searchParams.get('exp'));
    const sig = url.searchParams.get('sig') ?? '';

    expect(url.pathname).toBe('/media/icb/kyc/cus_1/passport-uid-1.png');
    expect(exp).toBe(1_700_000_300);
    expect(link.expiresAt).toBe('2023-11-14T22:18:20.000Z');
    expect(store.verifyDeliverySignature('icb/kyc/cus_1/passport-uid-1.png', exp, sig)).toBe(true);
    expect(store.verifyDeliverySignature('icb/kyc/cus_1/other.png', exp, sig)).toBe(false);
  });

  it('honours custom delivery prefix, secret, and a per-call TTL', async () => {
    const store = makeStore({
      deliveryPathPrefix: '/files',
      signingSecret: 'test-secret',
      deliveryUrlTtlSeconds: 60,
    });
    const ref = await savePassport(store);

    const link = store.buildSignedUrl(ref, 15, { download: true });
    expect(link.url.startsWith('http://localhost:3001/files/')).toBe(true);
    expect(link.url).toContain('&dl=1');
    expect(link.expiresAt).toBe('2023-11-14T22:13:35.000Z');
  });

  it('falls back to the configured TTL without a per-call override', async () => {
    const store = makeStore({ deliveryUrlTtlSeconds: 60 });
    const link = store.buildSignedUrl(await savePassport(store));
    expect(link.url).toContain(`exp=${String(1_700_000_060)}`);
    expect(link.url).not.toContain('dl=1');
  });
});

describe('destroy', () => {
  it('removes the persisted bytes', async () => {
    const store = makeStore();
    const ref = await savePassport(store);
    await store.destroy(ref);
    await expect(readFile(join(rootDir, 'icb/kyc/cus_1/passport-uid-1.png'))).rejects.toThrow();
  });

  it('is idempotent for an already-deleted asset', async () => {
    const store = makeStore();
    const ref = await savePassport(store);
    await store.destroy(ref);
    await expect(store.destroy(ref)).resolves.toBeUndefined();
  });
});
